routes/admin.php
<?php

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role']], function () {
    Route::get('/', function () {
        return view('home');
    })->name('admin-panel');
    Route::post('/categorygroup/updatesortorder', 'CategorygroupController@updateSortOrder')->name('categorygroup.updateSortOrder');
    Route::get('/categorygroup/categoriesInCategorygroup/{id}', 'CategorygroupController@categoriesInCategorygroup')->name('categorygroup.categories');
    Route::resource('/categorygroup', 'CategorygroupController');
    Route::get('/category/productsInCategory/{id}', 'CategoryController@productsInCategory')->name('category.products');
    Route::resource('/category', 'CategoryController');
    Route::get('/brand/productsInBrand/{id}', 'BrandController@productsInBrand')->name('brand.products');
    Route::resource('/brand', 'BrandController');
    Route::get('/measurment/parametersInMeasurment/{id}', 'MeasurmentController@parametersInMeasurment')->name('measurment.parameters');
    Route::resource('/measurment', 'MeasurmentController');
    Route::get('/parametergroup/parametersInParametergroup/{id}', 'ParametergroupController@parametersInParametergroup')->name('parametergroup.parameters');
    Route::resource('/parametergroup', 'ParametergroupController');
    Route::get('/parameter/productsInParameter/{id}', 'ParameterController@productsInParameter')->name('parameter.products');
    Route::resource('/parameter', 'ParameterController');
    Route::resource('/image', 'ImageController');
    Route::get('/product/cartsOfProduct/{id}', 'ProductController@cartsOfProduct')->name('product.carts');
    Route::get('/product/ordersOfProduct/{id}', 'ProductController@ordersOfProduct')->name('product.orders');
    Route::resource('/product', 'ProductController');
});

routes/web.php
<?php

// TODO: Stugel, ete group-um grum enq middleware => auth, petq e ardyoq amen mi rout-i hamar el grel ?

//User dashboard
Route::group(['middleware' => 'auth'], function () {
    Route::get('/cart', 'CartController@index')->name('cart.index');
    Route::post('/cart', 'CartController@store')->name('cart.store');
    Route::put('/cart', 'CartController@update')->name('cart.update');
    Route::delete('/cart/{id}', 'CartController@destroy')->name('cart.destroy');
    Route::get('/order', 'OrderController@index')->name('front.order');
});
//User dashboard

// Front routes
Route::group(['middleware' => 'web'], function () {
    Route::get('/', 'FrontController@index')->name('front');
    Route::get('/products', 'ProductController@index')->name('front.products'); // For ajax
    Route::get('/product/{productId}', 'ProductController@show')->name('front.product');
    Route::get('/brand/{brandUri}', 'BrandController@index')->name('front.brand');
    Route::get('/{categorygroupUri}', 'CategorygroupController@index')->name('front.categorygroup');
    Route::get('/{categorygroupUri}/{categoryUri}', 'CategoryController@index')->name('front.category');
    Route::get('/contact', 'ContactController')->name('contact');
    Route::post('/checkEmailExists', 'Auth\RegisterController@checkEmailExists')->name('checkEmailExists');
    Route::post('/pass/email', 'Auth\ResetPasswordController@sendPasswordResetEmail')->name('passwordreset.email');
    Route::post('/pass/reset', 'Auth\ResetPasswordController@resetPassword')->name('passwordreset.change');
    Route::get('/verify/token/{token}', 'Auth\VerificationController@verify')->name('auth.verify');
    Route::get('/verify/resend', 'Auth\VerificationController@resend')->name('auth.verify.resend');
    Route::auth();
    Auth::routes();
});

// Temporary route for inserting information in tables
Route::get('/temp', 'TempController@insert');
Route::post('/tempajax', 'TempController@ajax');

resources/views/admin/brand_index.blade.php
@extends('layouts.app')
@section('title','Brands')
@section('routes')
    <meta name="route_brandProducts" content="{{route('brand.products','')}}">
@endsection

@section('content')

    <div class="col-xs-12">
        <h1>All brands</h1>
        <hr>
    </div>
    <div class="col-xs-12">
        <a href="{{route('brand.create')}}" class="btn btn-success" role="button">
            <i class="fa fa-plus-square-o" aria-hidden="true"></i>
            Add brand
        </a>
        <br>
        <br>
    </div>
    <div class="col-xs-12">
        <table class="table table-bordered table-hover table-responsive" id="id_brandTable">
            <thead>
            <tr class="text-nowrap">
                <th class="text-center">@sortablelink('id','Id')</th>
                <th class="text-center">@sortablelink('name','Name')</th>
                <th class="text-center">@sortablelink('uri','URI')</th>
                <th class="text-center">@sortablelink('created_at','Created at')</th>
                <th class="text-center">@sortablelink('updated_at', 'Updated at')</th>
                <th class="text-center">Show</th>
                <th class="text-center">Edit</th>
                <th class="text-center">Delete</th>
            </tr>
            </thead>
            <tbody>
            @if(isset($brands) && is_object($brands))
                @foreach($brands as $brand)
                    <tr data-id="{{$brand->id}}">
                        <td> {{$brand->id}}</td>
                        <td> {{$brand->name}}</td>
                        <td> {{$brand->uri}}</td>
                        <td> {{$brand->created_at}}</td>
                        <td> {{$brand->updated_at}}</td>
                        <td class="text-center">
                            <a href="{{route('brand.show', $brand->id)}}"
                               data-toggle="tooltip" title="Show brand" class="btn btn-info btn-sm" role="button">
                                <i class="fa fa-window-maximize" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="{{route('brand.edit', $brand->id)}}"
                               data-toggle="tooltip" title="Update brand" class="btn btn-info btn-sm" role="button">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="#" data-toggle="tooltip" title="Delete brand"
                               class="btn btn-danger btn-sm delete"
                               role="button" data-deleteName="{{$brand->name}}"
                               data-deleteUrl="{{route('brand.destroy',$brand->id)}}"
                               data-id="{{$brand->id}}">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>
                @endforeach
            @endif
            </tbody>
        </table>
        {!! $brands->appends(\Request::except('page'))->render() !!}
    </div>

@endsection
@section('modals')
    @include('layouts.partials_admin.modal_delete')
@endsection

resources/views/admin/category_edit.blade.php
@extends('layouts.app')
@section('title','Edit category')

@section('content')
    <div class="col-xs-12">
        <h1>Edit category</h1>
        <hr>
    </div>
    <div class="col-xs-12">
        <form action="{{ route('category.update',$category->id) }}" method="post">
            <div class="row">
                {{ csrf_field() }}
                {{ method_field('PUT') }}

                <div class="col-xs-12">
                    <div class="row" id="id_allInputGroups" >
                        <div class="form-group col-xs-3 ">
                            <input name="name" type="text" id="category" class="form-control"
                                   value="{{$category->name}}" placeholder="Category name">
                        </div>
                        <div class="form-group col-xs-3 ">
                            <input name="uri" type="text" class="form-control"
                                   value="{{$category->uri}}" placeholder="URI">
                        </div>
                        <div class="form-group col-xs-3">
                            <select name="categorygroup_id" class="form-control">
                                <option value="0">Choose categorygroup</option>
                                @foreach($categorygroups as $id => $name)
                                    <option value="{{$id}}"
                                    @if($category->categorygroup_id == $id)
                                        {{'selected'}}
                                            @endif
                                    >
                                        {{$name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-small btn-success "><strong>STORE</strong></button>
                    </div>
                    <div class="form-group">
                        <a class="btn btn-small btn-primary" href="{{ route('category.index') }}"><strong>All
                                Categories</strong></a>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/category_index.blade.php
@extends('layouts.app')
@section('title','Categories')
@section('routes')
    <meta name="route_categoryProducts" content="{{route('category.products','')}}">
@endsection

@section('content')

    <div class="col-xs-12">
        <h1>All categories</h1>
        <hr>
    </div>
    <div class="col-xs-12">
        <a href="{{route('category.create')}}" class="btn btn-success" role="button">
            <i class="fa fa-plus-square-o" aria-hidden="true"></i>
            Add category
        </a>
        <br>
        <br>
    </div>
    <div class="col-xs-12">
        <table class="table table-bordered table-hover table-responsive" id="id_categoryTable">
            <thead>
            <tr class="text-nowrap">
                <th class="text-center">@sortablelink('id','Id')</th>
                <th class="text-center">@sortablelink('name','Name')</th>
                <th class="text-center">@sortablelink('uri','URI')</th>
                <th class="text-center">@sortablelink('categorygroup.name','Categorygroup')</th>
                <th class="text-center">@sortablelink('created_at','Created at')</th>
                <th class="text-center">@sortablelink('updated_at', 'Updated at')</th>
                <th class="text-center">Show</th>
                <th class="text-center">Edit</th>
                <th class="text-center">Delete</th>
            </tr>
            </thead>
            <tbody>
            @if(isset($categories) && is_object($categories))
                @foreach($categories as $category)
                    <tr data-id="{{$category->id}}">
                        <td> {{$category->id}}</td>
                        <td> {{$category->name}}</td>
                        <td> {{$category->uri}}</td>
                        <td> {{$category->categorygroup->name}}</td>
                        <td> {{$category->created_at}}</td>
                        <td> {{$category->updated_at}}</td>
                        <td class="text-center">
                            <a href="{{route('category.show', $category->id)}}"
                               data-toggle="tooltip" title="Show category" class="btn btn-info btn-sm" role="button">
                                <i class="fa fa-window-maximize" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="{{route('category.edit', $category->id)}}"
                               data-toggle="tooltip" title="Update category" class="btn btn-info btn-sm" role="button">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="#" data-toggle="tooltip" title="Delete category"
                               class="btn btn-danger btn-sm delete"
                               role="button" data-deleteName="{{$category->name}}"
                               data-deleteUrl="{{route('category.destroy',$category->id)}}"
                               data-id="{{$category->id}}">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>
                        </td>

                    </tr>
                @endforeach
            @endif
            </tbody>
        </table>
        {!! $categories->appends(\Request::except('page'))->render() !!}
    </div>

@endsection
@section('modals')
    @include('layouts.partials_admin.modal_delete')
@endsection

resources/views/admin/category_show.blade.php
@extends('layouts.app')
@section('title','Category show')
@section('routes')
    <meta name="route_categoryProducts" content="{{route('category.products','')}}">
@endsection

@section('content')

    <div class="col-xs-12">
        <h1>Category: "{{$category->name}}"</h1>
        <hr>
    </div>
    <div class="col-xs-12">
        <br>
    </div>
    <div class="col-xs-12">
        <table class="table table-bordered table-hover table-responsive" id="id_categoryTable">
            <thead>
            <tr class="text-nowrap">
                <th class="text-center">Id</th>
                <th class="text-center">Name</th>
                <th class="text-center">URI</th>
                <th class="text-center">Categorygroup</th>
                <th class="text-center">Products</th>
                <th class="text-center">Created at</th>
                <th class="text-center">Updated at</th>
                <th class="text-center">Edit</th>
                <th class="text-center">Delete</th>
            </tr>
            </thead>
            <tbody>
            @if(isset($category) && is_object($category))
                    <tr data-id="{{$category->id}}">
                        <td> {{$category->id}}</td>
                        <td> {{$category->name}}</td>
                        <td> {{$category->uri}}</td>
                        <td>{{$category->categorygroup->name}}</td>
                        <td>
                            @foreach($category->products as $product)
                                <p>{{$product->name}}</p>
                            @endforeach
                        </td>
                        <td> {{$category->created_at}}</td>
                        <td> {{$category->updated_at}}</td>
                        <td class="text-center">
                            <a href="{{route('category.edit', $category->id)}}"
                               data-toggle="tooltip" title="Update category" class="btn btn-info btn-sm" role="button">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="#" data-toggle="tooltip" title="Delete category"
                               class="btn btn-danger btn-sm delete"
                               role="button" data-deleteName="{{$category->name}}"
                               data-deleteUrl="{{route('category.destroy',$category->id)}}"
                               data-id="{{$category->id}}">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>
            @endif
            </tbody>
        </table>
        <div class="form-group">
        <a href="{{route('category.create')}}" class="btn btn-success" role="button">
            <i class="fa fa-plus-square-o" aria-hidden="true"></i>
            Add category
        </a>
    </div>
        <div class="form-group">
            <a class="btn btn-small btn-primary" href="{{ route('category.index') }}"><strong>All
                    Categories</strong></a>
        </div>
    </div>

@endsection
@section('modals')
    @include('layouts.partials_admin.modal_delete')
@endsection

resources/views/admin/categorygroup_index.blade.php
@extends('layouts.app')
@section('title','Categorygroups')
@section('routes')
    <meta name="route_categorygroupCategories" content="{{route('categorygroup.categories','')}}">
@endsection

@section('content')

    <div class="col-xs-12">
        <h1>All categorygroups</h1>
        <hr>
    </div>
    <div class="col-xs-12">
        <a href="{{route('categorygroup.create')}}" class="btn btn-success" role="button">
            <i class="fa fa-plus-square-o" aria-hidden="true"></i>
            Add categorygroup
        </a>
        <a href="{{route('categorygroup.create')}}" class="btn btn-primary pull-right" id="id_changeSortOrder"
           role="button">
            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
            Change sort order
        </a>
        <br>
        <br>
    </div>
    <div class="col-xs-12">
        <table class="table table-bordered table-hover table-responsive" id="id_categorygroupTable">
            <thead>
            <tr class="text-nowrap">
                <th class="text-center">#</th>
                <th class="text-center">Name</th>
                <th class="text-center">URI</th>
                <th class="text-center">Created at</th>
                <th class="text-center">Updated at</th>
                <th class="text-center">Show</th>
                <th class="text-center">Edit</th>
                <th class="text-center">Delete</th>
            </tr>
            </thead>
            <tbody>
            @if(isset($categorygroups) && is_object($categorygroups))
                @php
                    $i=1 ;
                @endphp
                @foreach($categorygroups as $categorygroup)
                    <tr data-id="{{$categorygroup->id}}">
                        <td> {{$i++}}</td>
                        <td> {{$categorygroup->name}}</td>
                        <td> {{$categorygroup->uri}}</td>
                        <td> {{$categorygroup->created_at}}</td>
                        <td> {{$categorygroup->updated_at}}</td>
                        <td class="text-center">
                            <a href="{{route('categorygroup.show', $categorygroup->id)}}"
                               data-toggle="tooltip" title="Update categorygroup" class="btn btn-info btn-sm" role="button">
                                <i class="fa fa-window-maximize" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="{{route('categorygroup.edit', $categorygroup->id)}}"
                               data-toggle="tooltip" title="Update categorygroup" class="btn btn-info btn-sm" role="button">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="#" data-toggle="tooltip" title="Delete categorygroup"
                               class="btn btn-danger btn-sm delete"
                               role="button" data-deleteName="{{$categorygroup->name}}"
                               data-deleteUrl="{{route('categorygroup.destroy',$categorygroup->id)}}"
                               data-id="{{$categorygroup->id}}">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>
                        </td>

                    </tr>
                @endforeach
            @endif
            </tbody>
        </table>

    </div>
    <div class="hidden">
        <form action="{{route('categorygroup.updateSortOrder')}}" method="POST" id="id_newSortOrderForm">
            {{ csrf_field() }}
        </form>
    </div>

@endsection
@section('modals')
    @include('layouts.partials_admin.modal_delete')
@endsection

@section('js_plugins')
    <script src="{{asset('js/jquery-ui.min.js')}}"></script>
@endsection

resources/views/admin/image_show.blade.php
@extends('layouts.app')
@section('title','Image show')
@section('routes')
    {{--<meta name="route_categoryProducts" content="{{route('category.products','')}}">--}}
@endsection

@section('content')
    <div class="col-xs-12">
        <h1>Image: "{{$image->name}}"</h1>
        <hr>
    </div>
    <div class="col-xs-12">
        <br>
    </div>
    <div class="col-xs-12">
        <table class="table table-bordered table-hover table-responsive" id="id_imageTable">
            <thead>
            <tr class="text-nowrap">
                <th class="text-center">Id</th>
                <th class="text-center">Name</th>
                <th class="text-center">Product</th>
                <th class="text-center">Main</th>
                <th class="text-center">Size</th>
                <th class="text-center">Created at</th>
                <th class="text-center">Updated at</th>
                <th class="text-center">Edit</th>
                <th class="text-center">Delete</th>
            </tr>
            </thead>
            <tbody>
            @if(isset($image) && is_object($image))
                <tr data-id="{{$image->id}}">
                    <td> {{$image->id}}</td>
                    <td> {{$image->name}}</td>
                    <td>{{$image->product->name}}</td>
                    <td>{{$image->main}}</td>
                    <td>{{$image->size}}</td>
                    <td> {{$image->created_at}}</td>
                    <td> {{$image->updated_at}}</td>
                    <td class="text-center">
                        <a href="{{route('image.edit', $image->id)}}"
                           data-toggle="tooltip" title="Update image" class="btn btn-info btn-sm" role="button">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        </a>
                    </td>
                    <td class="text-center">
                        <a href="#" data-toggle="tooltip" title="Delete image"
                           class="btn btn-danger btn-sm delete"
                           role="button" data-deleteName="{{$image->name}}"
                           data-deleteUrl="{{route('image.destroy',$image->id)}}"
                           data-id="{{$image->id}}">
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </a>
                    </td>
                </tr>
            @endif
            </tbody>
        </table>

        @if(isset($image) && is_object($image))
            <div class="row">
                <div class="form-group col-xs-8 col-sm-4">
                    <img src="{{route('front').'/'. $image->src}}" alt="{{$image->product->name}}"
                         class="img-responsive">
                </div>
            </div>
        @endif
        <div class="form-group">
            <a href="{{route('image.create')}}" class="btn btn-success" role="button">
                <i class="fa fa-plus-square-o" aria-hidden="true"></i>
                Add image
            </a>
        </div>
        <div class="form-group">
            <a class="btn btn-small btn-primary" href="{{ route('image.index') }}"><strong>All
                    Images</strong></a>
        </div>
    </div>

@endsection
@section('modals')
    @include('layouts.partials_admin.modal_delete')
@endsection

resources/views/admin/parameter_index.blade.php
@extends('layouts.app')
@section('title','Parameters')
@section('routes')
    <meta name="route_parameterProducts" content="{{route('parameter.products','')}}">
@endsection

@section('content')

    <div class="col-xs-12">
        <h1>All parameters</h1>
        <hr>
    </div>
    <div class="col-xs-12">
        <a href="{{route('parameter.create')}}" class="btn btn-success" role="button">
            <i class="fa fa-plus-square-o" aria-hidden="true"></i>
            Add parameter
        </a>
        <br>
        <br>
    </div>
    <div class="col-xs-12">
        <table class="table table-bordered table-hover table-responsive" id="id_parameterTable">
            <tr class="text-nowrap">
            <tr>
                <th class="text-center">@sortablelink('id','Id')</th>
                <th class="text-center">@sortablelink('name','Name')</th>
                <th class="text-center">@sortablelink('type','Type')</th>
                <th class="text-center">@sortablelink('measurment.name','Measurment')</th>
                <th class="text-center">@sortablelink('parametergroup.name','Parametergroup')</th>
                <th class="text-center">@sortablelink('created_at','Created at')</th>
                <th class="text-center">@sortablelink('updated_at', 'Updated at')</th>
                <th class="text-center">Show</th>
                <th class="text-center">Edit</th>
                <th class="text-center">Delete</th>
            </tr>
            </thead>
            <tbody>
            @if(isset($parameters) && is_object($parameters))
                @foreach($parameters as $parameter)
                    <tr data-id="{{$parameter->id}}">
                        <td> {{$parameter->id}}</td>
                        <td> {{$parameter->name}}</td>
                        <td> {{$parameter->type}}</td>
                        <td> {{$parameter->measurment->name}}</td>
                        <td> {{$parameter->parametergroup->name}}</td>
                        <td> {{$parameter->created_at}}</td>
                        <td> {{$parameter->updated_at}}</td>
                        <td class="text-center">
                            <a href="{{route('parameter.show', $parameter->id)}}"
                               data-toggle="tooltip" title="Show parameter" class="btn btn-info btn-sm" role="button">
                                <i class="fa fa-window-maximize" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="{{route('parameter.edit', $parameter->id)}}"
                               data-toggle="tooltip" title="Update parameter" class="btn btn-info btn-sm" role="button">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="#" data-toggle="tooltip" title="Delete parameter"
                               class="btn btn-danger btn-sm delete"
                               role="button" data-deleteName="{{$parameter->name}}"
                               data-deleteUrl="{{route('parameter.destroy',$parameter->id)}}"
                               data-id="{{$parameter->id}}">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>
                        </td>

                    </tr>
                @endforeach
            @endif
            </tbody>
        </table>
        {!! $parameters->appends(\Request::except('page'))->render() !!}

    </div>

@endsection
@section('modals')
    @include('layouts.partials_admin.modal_delete')
@endsection

resources/views/admin/parametergroup_index.blade.php
@extends('layouts.app')
@section('title','Parametergroups')
@section('routes')
    <meta name="route_parametergroupParameters" content="{{route('parametergroup.parameters','')}}">
@endsection

@section('content')

    <div class="col-xs-12">
        <h1>All parametergroups</h1>
        <hr>
    </div>
    <div class="col-xs-12">
        <a href="{{route('parametergroup.create')}}" class="btn btn-success" role="button">
            <i class="fa fa-plus-square-o" aria-hidden="true"></i>
            Add parametergroup
        </a>
        <br>
        <br>
    </div>
    <div class="col-xs-12">
        <table class="table table-bordered table-hover table-responsive" id="id_parametergroupTable">
            <thead>
            <tr class="text-nowrap">
                <th class="text-center">@sortablelink('id','Id')</th>
                <th class="text-center">@sortablelink('name','Name')</th>
                <th class="text-center">@sortablelink('created_at','Created at')</th>
                <th class="text-center">@sortablelink('updated_at', 'Updated at')</th>
                <th class="text-center">Show</th>
                <th class="text-center">Edit</th>
                <th class="text-center">Delete</th>
            </tr>
            </thead>
            <tbody>
            @if(isset($parametergroups) && is_object($parametergroups))

                @foreach($parametergroups as $parametergroup)
                    <tr data-id="{{$parametergroup->id}}">
                        <td> {{$parametergroup->id}}</td>
                        <td> {{$parametergroup->name}}</td>
                        <td> {{$parametergroup->created_at}}</td>
                        <td> {{$parametergroup->updated_at}}</td>
                        <td class="text-center">
                            <a href="{{route('parametergroup.show', $parametergroup->id)}}"
                               data-toggle="tooltip" title="Update parametergroup" class="btn btn-info btn-sm" role="button">
                                <i class="fa fa-window-maximize" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="{{route('parametergroup.edit', $parametergroup->id)}}"
                               data-toggle="tooltip" title="Update parametergroup" class="btn btn-info btn-sm" role="button">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="#" data-toggle="tooltip" title="Delete parametergroup"
                               class="btn btn-danger btn-sm delete"
                               role="button" data-deleteName="{{$parametergroup->name}}"
                               data-deleteUrl="{{route('parametergroup.destroy',$parametergroup->id)}}"
                               data-id="{{$parametergroup->id}}">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>
                        </td>

                    </tr>
                @endforeach
            @endif
            </tbody>
        </table>
        {!! $parametergroups->appends(\Request::except('page'))->render() !!}

    </div>

@endsection
@section('modals')
    @include('layouts.partials_admin.modal_delete')
@endsection

@section('js_plugins')
    <script src="{{asset('js/jquery-ui.min.js')}}"></script>
@endsection