routes/admin.php
<?php

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role']], function () {
    Route::get('/', function () {
        return view('home');
    })->name('admin-panel');
    Route::post('/categorygroup/updatesortorder', 'CategorygroupController@updateSortOrder')->name('categorygroup.updateSortOrder');
    Route::get('/categorygroup/categoriesInCategorygroup/{id}', 'CategorygroupController@categoriesInCategorygroup')->name('categorygroup.categories');
    Route::resource('/categorygroup', 'CategorygroupController');
    Route::get('/category/productsInCategory/{id}', 'CategoryController@productsInCategory')->name('category.products');
    Route::resource('/category', 'CategoryController');
    Route::get('/brand/productsInBrand/{id}', 'BrandController@productsInBrand')->name('brand.products');
    Route::resource('/brand', 'BrandController');
    Route::get('/measurment/parametersInMeasurment/{id}', 'MeasurmentController@parametersInMeasurment')->name('measurment.parameters');
    Route::resource('/measurment', 'MeasurmentController');
    Route::get('/parametergroup/parametersInParametergroup/{id}', 'ParametergroupController@parametersInParametergroup')->name('parametergroup.parameters');
    Route::resource('/parametergroup', 'ParametergroupController');
    Route::get('/parameter/productsInParameter/{id}', 'ParameterController@productsInParameter')->name('parameter.products');
    Route::resource('/parameter', 'ParameterController');
    Route::resource('/image', 'ImageController');
    Route::get('/product/cartsOfProduct/{id}', 'ProductController@cartsOfProduct')->name('product.carts');
    Route::get('/product/ordersOfProduct/{id}', 'ProductController@ordersOfProduct')->name('product.orders');
    Route::resource('/product', 'ProductController');
});

routes/web.php
<?php

// TODO: Stugel, ete group-um grum enq middleware => auth, petq e ardyoq amen mi rout-i hamar el grel ?

//User dashboard
Route::group(['middleware' => 'auth'], function () {
    Route::get('/cart', 'CartController@index')->name('cart.index');
    Route::post('/cart', 'CartController@store')->name('cart.store');
    Route::put('/cart', 'CartController@update')->name('cart.update');
    Route::delete('/cart/{id}', 'CartController@destroy')->name('cart.destroy');
    Route::get('/order', 'OrderController@index')->name('front.order');
});
//User dashboard

// Front routes
Route::group(['middleware' => 'web'], function () {
    Route::get('/', 'FrontController@index')->name('front');
    Route::get('/products', 'ProductController@index')->name('front.products'); // For ajax
    Route::get('/product/{productId}', 'ProductController@show')->name('front.product');
    Route::get('/brand/{brandUri}', 'BrandController@index')->name('front.brand');
    Route::get('/{categorygroupUri}', 'CategorygroupController@index')->name('front.categorygroup');
    Route::get('/{categorygroupUri}/{categoryUri}', 'CategoryController@index')->name('front.category');
    Route::get('/contact', 'ContactController')->name('contact');
    Route::post('/checkEmailExists', 'Auth\RegisterController@checkEmailExists')->name('checkEmailExists');
    Route::post('/pass/email', 'Auth\ResetPasswordController@sendPasswordResetEmail')->name('passwordreset.email');
    Route::post('/pass/reset', 'Auth\ResetPasswordController@resetPassword')->name('passwordreset.change');
    Route::get('/verify/token/{token}', 'Auth\VerificationController@verify')->name('auth.verify');
    Route::get('/verify/resend', 'Auth\VerificationController@resend')->name('auth.verify.resend');
    Route::auth();
    Auth::routes();
});

// Temporary route for inserting information in tables
Route::get('/temp', 'TempController@insert');
Route::post('/tempajax', 'TempController@ajax');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    @yield('routes')

    <title>@yield('title')</title>
    <!-- Styles -->
    <link rel="stylesheet" href="{{asset('css/font-awesome.min.css')}}">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('css/admin.css')}}">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    &nbsp;<li><a href="{{route('categorygroup.index')}}">Categorygroups</a></li>
                    <li><a href="{{route('category.index')}}">Categories</a></li>
                    <li><a href="{{route('brand.index')}}">Brands</a></li>
                    <li><a href="{{route('measurment.index')}}">Measurments</a></li>
                    <li><a href="{{route('parametergroup.index')}}">Parametergroups</a></li>
                    <li><a href="{{route('parameter.index')}}">Parameters</a></li>
                    <li><a href="{{route('image.index')}}">Images</a></li>
                    <li><a href="{{route('product.index')}}">Products</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @guest
                        <li><a href="{{ route('login') }}">Login</a></li>
                        <li><a href="{{ route('register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false" aria-haspopup="true" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                          style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-xs-12">

                @include('layouts.partials._notifications')
            </div>
        </div>
    </div>
    @yield('content')
</div>

{{--<!-- Additonal modals -->--}}
@yield('modals')
{{--<!-- /Additonal modals-->--}}

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
@yield('js_plugins')
<script src="{{asset('js/admin.js')}}"></script>
</body>
</html>

resources/views/layouts/front.blade.php
<!DOCTYPE html>
<html lang="{{app()->getLocale()}}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#178EA5">
    <meta name="csrf-token" content="{{csrf_token()}}">
    <meta name="pageName" content="@yield('pageName')">
    <meta name="route_login" content="{{route('login')}}">
    <meta name="route_register" content="{{route('register')}}">
    <meta name="route_passwordreset.email" content="{{route('passwordreset.email')}}">
    <meta name="route_passwordreset.change" content="{{route('passwordreset.change')}}">
    <meta name="route_checkEmailExists" content="{{route('checkEmailExists')}}">
    @yield('routes')
    @yield('additionalMeta')

    <title>@yield('title') | Core-Systems</title>
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/font-awesome.min.css')}}">
    @yield('css_plugins')
    <link rel="stylesheet" href="{{asset('css/index.css')}}">
    <link rel="stylesheet" href="{{asset('css/media.css')}}">

{{--    <link rel="shortcut icon" type="image/png" href="{{asset('images/favicon.ico')}}">--}}
    <link rel="shortcut icon" type="image/png" href="{{route('front')}}/images/favicon.ico">
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

{{--@include('layouts.partials._notifications')--}}

<!-- Button to top -->
@include('layouts.partials.button_to_top')
<!-- /Button to top -->

<!-- Header -->
@include('layouts.partials.header')
<!-- /Header -->

<!-- Carousel -->
@yield('carousel')
<!-- /Carousel -->

<!-- Main -->
<div class="container">
    <div class="row">
        <!-- Main Information -->
    @yield('content')
    <!-- /Main Information-->
    </div>
</div>
<!-- /Main -->

<!-- Footer -->
@include('layouts.partials.footer')
<!-- /Footer -->

<!-- Login and Register modal -->
@include('layouts.partials.login_register_modal')
<!-- /Login and Register modal -->
{{--@include('layouts.partials.password_reset_modal')--}}
{{--<!-- Additonal modals -->--}}
@yield('modals')
{{--<!-- /Additonal modals-->--}}

<script src="{{asset('js/jquery-3.2.1.min.js')}}"></script>
<script src="{{asset('js/bootstrap.min.js')}}"></script>
@yield('js_plugins')
<script src="{{asset('js/main.js')}}"></script>

<!-- Google map -->
@include('layouts.partials.google_map_script')
<!-- /Google map -->
</body>
</html>